Repository 42supporters-hackason/pair-pro, pull requests merged in 2022-08, with the labels that each got.

#171 refac: error message and get info from context
  api/schema.graphql
  api/src/context.ts
  api/src/graphql/Community.ts
  api/src/graphql/LearnedSkill.ts
  api/src/graphql/Message.ts
  api/src/graphql/Post.ts
  api/src/graphql/Profile.ts
Labels: BE

#162 パジネーションで要素数返す！+ キーワードフィルタリング
  api/nexus-typegen.ts
  api/schema.graphql
  api/src/graphql/Community.ts
  api/src/graphql/Post.ts
  api/src/graphql/Profile.ts
Labels: BE

#177 verification後も型に `undefined` が入らないように修正
  api/src/context.ts
  api/src/graphql/PairProgrammingCount.ts
  api/src/graphql/Post.ts
  api/src/graphql/Profile.ts
Labels: enhancement, BE

#179 新規メッセージの通知
  client/graphql/mutations.ts
  client/graphql/queries.ts
  client/src/components/PostCard/index.tsx
  client/src/gen/graphql-client.ts
  client/src/pages/client/chat.tsx
  client/src/pages/client/home.tsx
  client/src/pages/hooks/useChatHooks.ts
  client/src/pages/hooks/useHomeHooks.ts
Labels: FE

#183 最も使用されている言語の繋ぎこみ
  client/graphql/queries.ts
  client/src/gen/graphql-client.ts
  client/src/pages/client/statistics.tsx
  client/src/pages/hooks/useStatisticsHooks.ts
Labels: FE
